### ISSUE TITLE
Error: Access violation

### ISSUE THREAD

**Issue by Razva** [linuxserver/docker-doublecommander#5]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Guacamole -> DoubleCommander should work as expected, with no errors showing on access.

## Current Behavior
When accessing DoubleCommander we're greeted with an error stating *Error: Access violation*. Here's a screenshot: https://www.screencast.com/t/8JxlCLXs

## Steps to Reproduce
Start DoubleCommander via CLI or via Docker-Compose. Access the app via browser.

## Environment
**OS:** Debian 10
**CPU architecture:** arm64
**How docker service was installed:** From the distro's repo.
**Device:** Odroid HC4
**Extra OS info:**
- Linux version 5.11.0-odroid-arm64 (gcc-8 (Debian 8.3.0-6) 8.3.0, GNU ld (GNU Binutils for Debian) 2.31.1)  SMP PREEMPT Debian 5.11.18-202108050550~buster (2021-08-04)
- Docker version 18.09.1, build 4c52b90

## Command used to create docker container (run/create/compose/screenshot)
Using `docker-compose.yml`:

```
version: "2.1"
services:
  doublecommander:
    image: ghcr.io/linuxserver/doublecommander
    container_name: doublecommander
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /home/razvanr/doublecommander:/config
      - /home/razvanr:/data
    ports:
      - 8086:3000
    restart: unless-stopped
```

## Docker logs
Logfile here: http://sprunge.us/Rcye2Z

## Permissions
```
# ls -la /home/razvanr/
drwxr-xr-x 8 razvanr razvanr 4096 Aug 13 17:20 doublecommander

# ls -la /home/razvanr/doublecommander/
total 56
drwxr-xr-x 8 razvanr razvanr  4096 Aug 13 17:20 .
drwxr-xr-x 5 razvanr razvanr  4096 Aug 13 17:19 ..
-rw-r--r-- 1 razvanr razvanr  2408 Aug 13 17:19 .bashrc
drwxrwxr-x 3 razvanr razvanr  4096 Aug 13 17:20 .cache
drwxr-xr-x 5 razvanr razvanr  4096 Aug 13 17:20 .config
drwx------ 3 razvanr razvanr  4096 Aug 13 17:20 .dbus
drwx------ 3 razvanr razvanr  4096 Aug 13 17:20 .local
-rw-r--r-- 1 razvanr razvanr 13347 Aug 13 17:20 .xorgxrdp.10.log
drwxr-xr-x 2 root    root     4096 Aug 13 17:19 custom-cont-init.d
drwxr-xr-x 2 root    root     4096 Aug 13 17:19 custom-services.d
-rwxr-xr-x 1 razvanr razvanr    82 Aug 13 17:19 startwm.sh
```
